# =================================================================
#
# Authors: Maxime Carre <maxime.carre@dfo-mpo.gc.ca>
#
# =================================================================

server:
  bind:
      host: 0.0.0.0  # listening address for incoming connections
      port: 5000  # listening port for incoming connections
  url: http://localhost:5000/  # url of server
  mimetype: application/json; charset=UTF-8  # default MIME type
  encoding: utf-8  # default server encoding
  language: en-US  # default server language
  cors: true  # boolean on whether server should support CORS
  pretty_print: true  # whether JSON responses should be pretty-printed
  limit: 10  # server limit on number of items to return
  map:  # leaflet map setup for HTML pages
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
  ogc_schemas_location: http://schemas.opengis.net 

logging:
  level: ERROR
  logfile: ./logs/pygeoapi.log

metadata:
    identification:
        title: CHS Pygeoapi  # the title of the service
        description: pygeoapi provides an API to geospatial data  # some descriptive text about the service
        keywords:  # list of keywords about the service
            - geospatial
            - data
            - api
        keywords_type: theme  # keyword type as per the ISO 19115 MD_KeywordTypeCode codelist. Accepted values are discipline, temporal, place, theme, stratum
        terms_of_service: https://creativecommons.org/licenses/by/4.0/  # terms of service
        url: http://example.org  # informative URL about the service
    license:  # licensing details
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:  # service provider details
        name: Canadian Hydrographic Service
        url: https://www.charts.gc.ca/
    contact:  # service contact details
        name: Carre, Maxime
        position: Physical Scientist
        address: 9860 W Saanich Rd
        city: Sidney 
        stateorprovince: BC
        postalcode: V8L 4B2
        country: Canada
        phone: +1-250-363-6363
        email: maxime.carre@dfo-mpo.gc.ca
        hours: Mo-Fr 08:00-17:00 PST
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:
    iwls:
        type: collection  # REQUIRED (collection, process, or stac-collection)
        title: Waterlevel  # title of dataset
        description: Observation, Forecast and Prediction  # abstract of dataset
        keywords:  # list of related keywords
            - observations
            - water level
        context:  # linked data configuration (see Linked Data section)
            - datetime: https://schema.org/DateTime
            - vocab: https://example.com/vocab#
              stn_id: "vocab:stn_id"
              value: "vocab:value"
        links:  # list of 1..n related links
            - type: text/csv  # MIME type
              rel: canonical  # link relations per https://www.iana.org/assignments/link-relations/link-relations.xhtml
              title: data  # title
              href: https://api-iwls.dfo-mpo.gc.ca/  # URL
              hreflang: en-US  # language
        extents:  # spatial and temporal extents
            spatial:  # required
                bbox: [-180,-90,180,90]  # list of minx, miny, maxx, maxy
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84  # CRS
            temporal:  # optional
                begin: 1900-01-01T00:00:00Z  # start datetime in RFC3339
                end: 2100-01-01T00:00:00Z  # end datetime in RFC3339
        providers:  # list of 1..n required connections information
            # provider name
            # see pygeoapi.plugin for supported providers
            # for custom built plugins, use the import path (e.g. mypackage.provider.MyProvider)
            # see Plugins section for more information
            - type: feature # underlying data geospatial type: (allowed values are: feature, coverage, record, tile, edr)
              default: true  # optional: if not specified, the first provider definition is considered the default
              name: provider_iwls.provider_iwls.ProviderIwls
              data: https://api-iwls.dfo-mpo.gc.ca/api/  # required: the data filesystem path or URL, depending on plugin setup
              id_field: id  # required for vector data, the field corresponding to the ID
              title_field: id # optional field of which property to display as title/label on HTML pages
              format:  # optional default format
                  name: GeoJSON  # required: format name
                  mimetype: application/json  # required: format mimetype
    s104:
        type: process
        processor:
            name: provider_iwls.s104.S104Processor

    hello-world:
        type: process
        processor:
            name: HelloWorld